import { ToastContainer } from 'react-toastify';
import { StoreProvider } from '@/store/StoreProvider';

import './../style/index.scss';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <StoreProvider>
        <html lang="en">
          <body>
            {children}
            <ToastContainer />
          </body>
        </html>
      </StoreProvider>
    </>
  )
}
